name: build

on:
    push:
        branches:
            - live
        paths:
            - ".github/workflows/build.yml"
            - "biome.json"
            - "commitlint.config.ts"
            - "cspell.yml"
            - "index.html"
            - "package.json"
            - "pnpm-*.yaml"
            - "public/**"
            - "src/**"
            - "tsconfig.json"
            - "vite*.*.ts"
    pull_request:
        paths:
            - ".github/workflows/build.yml"
            - "biome.json"
            - "commitlint.config.ts"
            - "cspell.yml"
            - "index.html"
            - "package.json"
            - "pnpm-*.yaml"
            - "public/**"
            - "src/**"
            - "tsconfig.json"
            - "vite*.*.ts"
    workflow_dispatch:

env:
    CI: 1

jobs:
    build:
        if: github.actor != 'dependabot[bot]'
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: Install pnpm
              uses: pnpm/action-setup@v5.0.0

            - name: Install dependencies
              run: pnpm install

            - name: Run the CI script
              run: pnpm run ci
